Repository haffi96/encapsulate, pull requests merged in 2022-03, with the labels that each got.

#12 Add firebase
  .gitignore
  backend/__init__.py
  backend/alembic.ini
  backend/alembic/README
  backend/alembic/env.py
  backend/alembic/script.py.mako
  backend/alembic/versions/bd57fc2825f6_first_migrate.py
  backend/crud.py
  backend/database.py
  backend/main.py
  backend/models.py
  backend/requirements.txt
  backend/schemas.py
  backend/sqlite.db
  docs/vault/TODOs.md
  docs/vault/config.js.md
  frontend/.gitignore
  frontend/App.js
  frontend/components/Task.js
  frontend/config.js
  frontend/context/AuthContext.js
  frontend/firebase.js
  frontend/package-lock.json
  frontend/package.json
  frontend/requests/login.js
  frontend/screens/HomeScreen.js
  frontend/screens/LoginScreen.js
  frontend/screens/TodoScreen.js
  frontend/services/collections.js
Labels: database

#19 14 add bottom tabs for navigation
  frontend/App.jsx
  frontend/firebase.js
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/GymLogScreen.js
  frontend/screens/GymLogScreen.jsx
  frontend/screens/HomeScreen.jsx
  frontend/screens/LoginScreen.jsx
  frontend/screens/TodoScreen.jsx
Labels: enhancement

#23 11-strike-through-animate-checked-todos
  frontend/components/Task.jsx
Labels: enhancement

#22 Notes navigation and buttons
  frontend/App.jsx
  frontend/babel.config.js
  frontend/components/Note.jsx
  frontend/package-lock.json
  frontend/package.json
  frontend/screens/Notes/AllNotesScreen.jsx
  frontend/screens/Notes/CreateNoteScreen.jsx
  frontend/screens/Notes/NoteScreen.jsx
  frontend/screens/TodoScreen.jsx
  frontend/services/collections.js
Labels: enhancement

#34 Bin icon for deletes
  frontend/components/Note.jsx
  frontend/components/Task.jsx
Labels: enhancement

#38 readme
  README.md
Labels: documentation
